#if !defined(AFX_AGENTCTLAUDIOOBJECTEX_H__38A1EFF4_6440_4F2A_81E1_EF04F88C0DD8__INCLUDED_)
#define AFX_AGENTCTLAUDIOOBJECTEX_H__38A1EFF4_6440_4F2A_81E1_EF04F88C0DD8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlAudioObjectEx wrapper class

class CAgentCtlAudioObjectEx : public COleDispatchDriver
{
public:
	CAgentCtlAudioObjectEx() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlAudioObjectEx(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlAudioObjectEx(const CAgentCtlAudioObjectEx& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetEnabled();
	BOOL GetSoundEffects();
	short GetStatus();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLAUDIOOBJECTEX_H__38A1EFF4_6440_4F2A_81E1_EF04F88C0DD8__INCLUDED_)
