#if !defined(AFX_FDIMAGE_H__F436A27A_2623_41B5_A635_37176F04E821__INCLUDED_)
#define AFX_FDIMAGE_H__F436A27A_2623_41B5_A635_37176F04E821__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class C_Collection;

/////////////////////////////////////////////////////////////////////////////
// CfdImage wrapper class

class CfdImage : public CWnd
{
protected:
	DECLARE_DYNCREATE(CfdImage)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa920dec5, 0xa3f6, 0x4057, { 0xb4, 0x5, 0x70, 0xe5, 0xf1, 0xa1, 0xe1, 0xa3 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetFlatToolbar();
	void SetFlatToolbar(BOOL bNewValue);
	short GetFilterIndex();
	void SetFilterIndex(short nNewValue);
	CString GetFilter();
	void SetFilter(LPCTSTR lpszNewValue);
	C_Collection GetFileNames();
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	long ShowOpen();
	CString GetCancelButtonCaption();
	void SetCancelButtonCaption(LPCTSTR lpszNewValue);
	CString GetDialogTitle();
	void SetDialogTitle(LPCTSTR lpszNewValue);
	CString GetDefaultExt();
	void SetDefaultExt(LPCTSTR lpszNewValue);
	long GetFlags();
	void SetFlags(long nNewValue);
	long GetStartupPosition();
	void SetStartupPosition(long nNewValue);
	CString GetOkButtonCaption();
	void SetOkButtonCaption(LPCTSTR lpszNewValue);
	long GetMaxFileSize();
	void SetMaxFileSize(long nNewValue);
	CString GetInitDir();
	void SetInitDir(LPCTSTR lpszNewValue);
	long GetHInstance();
	void SetHInstance(long nNewValue);
	long GetHHandle();
	void SetHHandle(long nNewValue);
	long GetCommDlghWnd();
	CString GetHelpKey();
	void SetHelpKey(LPCTSTR lpszNewValue);
	CString GetHelpFile();
	void SetHelpFile(LPCTSTR lpszNewValue);
	BOOL GetShowPreview();
	void SetShowPreview(BOOL bNewValue);
	long GetView();
	void SetView(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FDIMAGE_H__F436A27A_2623_41B5_A635_37176F04E821__INCLUDED_)
