#if !defined(AFX_GIF_H__82C9ABE1_F7E3_11D6_B343_EC522F277049__INCLUDED_)
#define AFX_GIF_H__82C9ABE1_F7E3_11D6_B343_EC522F277049__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGif wrapper class

class CGif : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGif)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x28d47530, 0xcf84, 0x11d1, { 0x83, 0x4c, 0x0, 0xa0, 0x24, 0x9f, 0xc, 0x28 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetEnabled(BOOL bNewValue);
	BOOL GetEnabled();
	long GetWindow();
	void Play();
	void Stop();
	BOOL GetAutoStart();
	void SetAutoStart(BOOL bNewValue);
	long GetSpeed();
	void SetSpeed(long nNewValue);
	BOOL GetGlass();
	void SetGlass(BOOL bNewValue);
	void SetAutoSize(BOOL bNewValue);
	BOOL GetAutoSize();
	BOOL GetEmbed();
	void SetEmbed(BOOL bNewValue);
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GIF_H__82C9ABE1_F7E3_11D6_B343_EC522F277049__INCLUDED_)
