//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FPAnalysis.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDD_PROGRESS                 102
#define IDD_SKINDIALOG_DIALOG           105
#define IDR_MAINFRAME                   128
#define IDR_FPANALTYPE                  129
#define IDD_CONVOLUTION                 133
#define IDB_LOGO                        138
#define IDD_BITMAPINFO                  139
#define IDD_SCAN                        140
#define IDB_FPSPLASH                    143
#define IDB_ABOUT                       144
#define IDD_DISPLAY                     146
#define IDB_LEFTHAND                    151
#define IDB_RIGHTHAND                   152
#define IDD_FINGERDATA                  153
#define IDI_HELP                        157
#define IDD_DUMMY                       165
#define IDD_AGENT_DIALOG                168
#define IDB_HISTOGRAM                   170
#define IDD_WIZP1HISTOGRAM              171
#define IDD_WIZP2GAUSSIAN               173
#define IDC_EDIT1                       1002
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_EDIT2                       1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_EDIT3                       1004
#define IDC_EDIT4                       1005
#define IDC_EDIT5                       1006
#define IDC_EDIT6                       1007
#define IDC_EDIT7                       1008
#define IDC_EDIT8                       1009
#define IDC_EDIT9                       1010
#define IDC_EDIT10                      1011
#define IDC_EDIT11                      1012
#define IDC_EDIT12                      1013
#define IDC_EDIT13                      1014
#define IDC_EDIT14                      1015
#define IDC_EDIT15                      1016
#define IDC_EDIT16                      1017
#define IDC_EDIT17                      1018
#define IDC_EDIT18                      1019
#define IDC_EDIT19                      1020
#define IDC_EDIT20                      1021
#define IDC_EDIT21                      1022
#define IDC_EDIT22                      1023
#define IDC_EDIT23                      1024
#define IDC_EDIT24                      1025
#define IDC_EDIT25                      1026
#define IDC_COMBO_FILTER                1030
#define IDC_SLIDER_SHARP                1032
#define IDC_STATIC_SHARP                1033
#define IDC_STATIC2                     1034
#define IDC_STATIC3                     1035
#define IDC_STATIC4                     1036
#define IDC_HEIGHT                      1037
#define IDC_WIDTH                       1038
#define IDC_BPP                         1039
#define IDC_COMPRESSION                 1040
#define IDC_STATIC6                     1041
#define IDC_IMAGESIZE                   1042
#define IDC_COLORSUSED                  1043
#define IDC_SELECTSCANNER               1044
#define IDC_STARTSCANNER                1045
#define IDC_BROWSE                      1046
#define IDC_FINGERPRINTSCAN             1047
#define IDC_IMAGEPATH                   1048
#define IDC_IMGEDIT                     1049
#define IDC_CREDIT                      1051
#define IDC_GIF891                      1052
#define IDC_DISPLAY_STATIC              1053
#define IDC_SKIN2                       1056
#define IDC_RADIO1                      1057
#define IDC_RADIO2                      1058
#define IDC_RADIO3                      1059
#define IDC_RADIO4                      1060
#define IDC_RADIO5                      1061
#define IDC_RADIO6                      1062
#define IDC_RADIO7                      1063
#define IDC_RADIO8                      1064
#define IDC_RADIO9                      1065
#define IDC_RADIO10                     1066
#define IDC_RADIO11                     1067
#define IDC_RADIO12                     1068
#define IDC_IPADDRESS1                  1069
#define IDC_ANIGIF1                     1070
#define IDC_EDIT_HELP                   1071
#define IDC_ANIGIF2                     1073
#define IDC_CAPTION                     1074
#define IDC_AGENTCONTROL                1075
#define IDC_CONTROL1                    1076
#define IDC_BUTTON1                     1077
#define IDC_LABEL1                      1078
#define ID_VIEW_GRAY                    32771
#define ID_WINDOW_FIT                   32772
#define ID_VIEW_THIN                    32773
#define ID_VIEW_BINARY                  32775
#define ID_VIEW_NEGATIVE                32776
#define ID_VIEW_RANGECOMPRESS           32777
#define ID_VIEW_CONVOLVE                32778
#define ID_VIEW_EDGE                    32779
#define ID_VIEW_EQUALIZE                32780
#define ID_WINDOW_ZOOMIN                32781
#define ID_WINDOW_ZOOMOUT               32784
#define ID_VIEW_BLURR                   32791
#define ID_VIEW_NORMALIZE               32792
#define ID_VIEW_ORIENTATION             32793
#define ID_VIEW_THINNING                32794
#define ID_HELP_HELP                    32796
#define ID_VIEW_ADAPTIVEBINARIZE        32797
#define ID_HELP_ABOUT                   32798
#define ID_VIEW_EXTRACTION              32799
#define ID_VIEW_DOCUMENTINFO            32800
#define ID_VIEW_ROI                     32801
#define ID_FILE_SCAN                    32803
#define ID_EDIT_DATA                    32805
#define ID_VIEW_SEGMENTATION            32806
#define ID_VIEW_CORE                    32807
#define ID_VIEW_MODELESS                32809
#define ID_VIEW_WIZARD                  32810
#define ID_ACTION_REGIONOFINTEREST      32811
#define ID_ACTION_FILTERAFTERMINUTIAEEXTRACTION 32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
